version: 2.1
jobs:
  build:
    docker:
      - image: circleci/clojure:tools-deps-1.9.0.394
    steps:
      - checkout
      - restore_cache:
          key: v1-ksml-{{checksum "deps.edn"}}
      - run: clojure -A:test
      - save_cache:
          paths:
            - ~/.m2
          key: v1-ksml-{{checksum "deps.edn" }}
