version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: clojure:tools-deps
    steps:
      - checkout
      - restore_cache:
          key: project-{{checksum "deps.edn" }}
      - run: clj -A:test
      - save_cache:
          paths:
            - ~/.m2
          key: project-{{checksum "deps.edn" }}
